#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bilibili
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  devtools:
    restart:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379

#rocketmq
rocketmq.name.server.address=127.0.0.1:9876

server:
  port: 15005



fdfs:
  tracker-list: 192.168.200.130:22122
  http:
    storage-addr: http://192.168.200.130:8888/group1/