#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bilibili
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  devtools:
    restart:
      enabled: true